command:
  - streamlit
  - run
  - app_picks.py
  - --server.address
  - 0.0.0.0
  - --server.port
  - $DATABRICKS_APP_PORT
env:
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: 'false'
  - name: GOAROUND_CACHE_DIR
    value: 'data/cache'
  - name: USE_DATABRICKS_SQL
    value: 'false'
